Remove dependency of "inspect" module.
Tested with QGis 3.2 64 bit from qgis.org on Windows 10 Home.
Tested with QGis 3.2 from "deb http://qgis.org/ubuntugis/ xenial main" on Ubuntu 16.04
Fixes the following error with QGis 3.2 on Windows:
'''
Couldn't load plugin 'GeoCoding' due to an error when calling its initGui() method 
NameError: name 'inspect' is not defined 
'''